SLACK_TOKEN=YOUR-SLACK-TOKEN
DATADOG_API_KEY=YOUR-API-KEY
DATADOG_APP_KEY=YOUR-APP-KEY
DATADOG_BOARD_ID=YOUR-BOARD-ID
# The widget id of the image you want to push to
DATADOG_WIDGET_NUMBER=YOUR-WIDGET-NUMBER

